### ISSUE TITLE
Edit Folders Screen : Document : Non dynamic document is getting displayed in the edit folders with web icon symbol 

### ISSUE THREAD

**Issue by MustafaASK** [ShaikASK/Testing#1037]
Steps To Replicate : 

1.Launch the URL
2.Sign in as HR admin user 
3.Upload a ”Document” with “Dynamic Webform” settings
4.Navigate to Edit Dynamic Webform screen 
5.Provide mapping from “Edit Dynamic webform’ screen  and save it
6.Check the above uploaded document in the folders  (displayed with web icon symbol)
7.Edit the above uploaded document by removing ‘Dynamic Webform” settings 
8.Go to Folders an check the document in the folders screen (document will be displayed expected)
9.Add the document in the folder and save it 
10..Edit the above created folder 

Experienced Behavior : Observed that Non dynamic document is getting displayed in the edit folders with web icon symbol 
Expected Behavior : Ensure that Non dynamic document should not display with web icon symbol in the edit folders screen

**Comment by ShaikASK** [comment]
DEV Team : Will be fixed in v4.1 (2nd test cycle)

**Comment by MustafaASK** [comment]
05/06/2019 - Natasha Chouhan - We have retested this on the latest Release#4 Build 2 and observed that this is working as expected , Hence marking this to close
