### ISSUE TITLE
:Candidate Dashboard : BGV Dynamic Webform document : User is unable to submit BGV document

### ISSUE THREAD

**Issue by MustafaASK** [ShaikASK/Testing#1170]
Steps To Replicate : 
1.Launch the URL
2.Sign in as Candidate 
3.Sign the Offer Letter 
4.Navigate to “Common Details” webform
5.Fill all the required webform 
6.Navigate to “Candidate Dashboard” 
7.Click on “Start” button displayed against “BGV” dynamic webform document 
8.Navigate to “BGV” document 
9.Click on “Submit” button 

Experienced Behavior : Observed that user is unable to submit BGV document in safari browser (Refer Screen Shot)
Expected Behavior : Ensure that user should be able to submit the document 

Please Refer Below Details to replicate this issue 
URL : http://192.168.1.197:8900/onboarding-new/#/login
Email Id : testing02@gmaill.com
Password : 123

![Screen Shot 2019-07-05 at 4 45 26 PM](https://user-images.githubusercontent.com/31955617/60719330-f3e56380-9f44-11e9-85de-6caa98791501.png)

**Comment by ShaikASK** [comment]
This is not an issue and this is not related to Safari issue.
Make both webform address maxlength same i.e. Both Webforms one is design webform(BGV->Employment details) Address_1-> maxlength and another one PDF webform Address_1 maxlength should be same
![issue](https://user-images.githubusercontent.com/31955547/60794067-8e80b500-a186-11e9-97c3-03d13d409ad3.jpg)

**Comment by MustafaASK** [comment]
10/07/2019 - Natasha Chouhan - We have retested this on the latest Beta Release #5 Build 1 and observed that this is working as expected , Hence marking this to close
