### ISSUE TITLE
BGV Webform : Educational Details screen:  The screen name displayed as  “Educational Details Details” instead of “Education Details”

### ISSUE THREAD

**Issue by MustafaASK** [ShaikASK/Testing#1290]
Steps To Replicate : 
1.Launch the URL
2.Sign in as HR admin user’
3.Go to Design webform 
4.Update BGV Education Sub webform Name to Education Details and save it
5.Create a New Hire and initiate it 
6.Sign in as candidate 
7.Sign the “Offer Letter”
8.Navigate to Common Details webform and click on Next button 
9.Navigate to “BGV” webform 
10.Click on+ icon displayed beside Education Details
11.Navigate to popup window ,check the title of popup window 

Experienced Behaviour : Observed that The screen name displayed as  “Educational Details Details” whereas actual form name given  in design web forms as “Education Details”.
Expected Behaviour : Ensure that it should display same name provided from design webform screen

**Comment by ShaikASK** [comment]
@Anil : As per Manish requirement, we changed it to Highest Education. And it is in Production. So you can marked it to Close.

**Comment by MustafaASK** [comment]
10/09/2019 - Natasha Chouhan - We have retested this on the latest Release #5 Build #55 and observed that this is working as expected , Hence marking this to close
