### ISSUE TITLE
New Hire : HR user is able to perform "Initiate Onboarding" when the Hire category is "c2c" and in workflow we have selected "Payroll package form"

### ISSUE THREAD

**Issue by MustafaASK** [ShaikASK/Testing#357]
Steps to Replicate 

1. Launch the url 
2. Login as Admin user 
3. Navigate to settings menu >> select documents 
4. Create a document with the following settings
Contractor Information  -----Yes 
HR Certification with upload Document ----Yes
5. Create a folder with the above document
6. Create workflow with the above folder and document and with the below settings
Common details ------- default yes 
Contractor Information ---yes
Payroll ------yes 
7. Create a new Hire with the above workflow and click on initiate onboarding 

Experienced  Behavior : Observed that Hr user is able to initiate onboarding with out any errors or alerts 
Expected Behavior : Ensure that user should not be allowed to perform "Initiate Onboarding" when the workflow setting is selected as payroll

**Comment by ShaikASK** [comment]
Vinay: This validation in Initiate Onboarding will be based on document settings which are in the workflow.

**Comment by MustafaASK** [comment]
Mahesh Varala - This is working as expected , Hence marking this to passed
