### ISSUE TITLE
Calendars : Task with future date getting displayed in red colour 

### ISSUE THREAD

**Issue by MustafaASK** [ShaikASK/Testing#455]
Steps : 

1. Launch the the URL
2. Sign in as HR Admin user 
3. Create a Task with some future date ( 1/Jan/2020) and save it 
4. Click on "Calendars" tab 
5. Check the Calendar for 1/Jan/2020 

Experienced Behaviour : Observed that future date getting displayed in red colour

**Comment by ShaikASK** [comment]
Vinay: This is behaving as expected, Events will be inblue color, Task in Open will be red,completed will be grayed

**Comment by MustafaASK** [comment]
21/06/2018 - Natasha Chouhan - We have retested this on the latest Release#3 Build 4 and observed that this is working as expected , Hence marking this to close
