### ISSUE TITLE
Edit New Hire : User is able to save New Hire without selecting "Client City" name which is mandatory field

### ISSUE THREAD

**Issue by ShaikASK** [ShaikASK/Testing#494]
Steps : 

1. Launch the URL
2. Sign in as HR Admin user 
3. Create a New Hire and save it 
4. Edit the above create New Hire
5. Change "Client State" name from drop down list

Experienced Behaviour : Observed that empty client city is displayed and hence user is able to save New Hire without selecting client city name which is mandatory field 
Experienced Behaviour : Ensure that application should not allow user to save new hire without entering  all mandatory fields

**Comment by MustafaASK** [comment]
2/07/2018 - Natasha Chouhan - We have retested this on the latest Release#3 Build 9 and observed that this is working as expected , Hence marking this to close
