### ISSUE TITLE
Safari 11 : New Hire : Vertical scroll bar is missing in New Hire screen 

### ISSUE THREAD

**Issue by ShaikASK** [ShaikASK/Testing#495]
Steps to Replicate : 

Launch the URL
Sign in as HR Admin user 
Create a New Hire 

Experienced Behaviour : Observed that application is not displaying vertical scroll bar in "New Hire" screen 
Expected Behaviour : Observed that application should display vertical scroll bar in "New Hires" screen

**Comment by MustafaASK** [comment]
Mahesh Varala - We have retested the issue and observed that it is working as expected , hence marking this to close
