### ISSUE TITLE
FF (61) : 1024 x 768 : Resolution Dashboard : Only four New Hires are visible instead of displaying  five New Hire on the dashboard screen 

### ISSUE THREAD

**Issue by MustafaASK** [ShaikASK/Testing#518]
Issue 01: Only four New Hires are visible instead of displaying  five New Hire on the dashboard screen 

Steps  to Replicate : 

1. Switch to 1024x768 resolution 
2. Launch the URL
3. Sign in as HR admin user
4. Create any 5 new hire and initiate it 
5. Check the "Dashboard" screen 

Experienced Behavior : Observed that Only four New Hires are visible on the dashboard screen with 1024 x 768 resolution 
Expected Behavior : Ensure that application should display 5 new hires on the dashboard screen with 1024x 768 resolution 

![v](https://user-images.githubusercontent.com/31955617/42566943-e2731c76-8525-11e8-8b65-b70f2d7477bf.jpg)

Issue 02 : IE(110 & FF(61) : Horizontal scroll bar is being displayed in Initiate New Hire Screen when check in 1024 x 768 resolution 

Steps to Replicate : 

1. Switch to 1024 x 768 resolution 
2. Sign in as HR admin user
3. Create New hire Initiate New hire 

Experienced Behavior : Observed that  Horizontal scroll bar is being displayed in Initiate New Hire Screen when check in 1024 x 768 resolution in IE (11) and FF(61) browsers 
Expected Behavior : Ensure that application should not display Horizontal scroll bar

**Comment by ShaikASK** [comment]
Vinay: Fixed in Dev Environment, will be released to QA in next build (30-7-2018 7:13 PM)

**Comment by MustafaASK** [comment]
01/08/2018 - Natasha Chouhan - We have retested this on the latest Release#3 Build 17 and observed that this is working as expected , Hence marking this to close
