### ISSUE TITLE
IE (11) / FF (61) : Initiate New Hire : Edit Workflow steps : Document name text alignment is missing upon clicking on edit workflow step 

### ISSUE THREAD

**Issue by MustafaASK** [ShaikASK/Testing#534]
Steps to Replicate : 

1. Launch the URL
2. Sign in as HR admin user 
3. Create a Workflow and enable Documents editable while Initiate Onboarding? radio option and save it 
4. Create New Hire 
5.  Initiate the above created New Hire 
6. Click on Edit icon present under edit workflows step 
7. Navigate to Edit step popup window 

Experienced Behavior : Observed that  document name text alignment is missing upon clicking on edit workflow step (Refer Screen Shot) 
Expected Behavior : Ensure that application should display proper alignment of documents

IE 
![ie](https://user-images.githubusercontent.com/31955617/43075273-ecd3d65c-8e9d-11e8-8280-daf42db8f625.jpg)

FF : In FF browser only document name text and cross symbol alignment is missing 
![ff](https://user-images.githubusercontent.com/31955617/43075284-f3f196ea-8e9d-11e8-9b3b-184b3e64c01b.jpg)

**Comment by ShaikASK** [comment]
31/07/2018 - Aditya - Fixed in Dev Environment. Will be released in next Build QA.

**Comment by MustafaASK** [comment]
01/08/2018 - Natasha Chouhan - We have retested this on the latest Release#3 Build 17 and observed that this is working as expected , Hence marking this to close
