### ISSUE TITLE
Folders : Documents : User is still able to see all the documents in folders when all the mapping is removed 

### ISSUE THREAD

**Issue by MustafaASK** [ShaikASK/Testing#547]
Steps to Replicate : 

1. Launch the URL
2. Sign in as HR Admin user
3. Upload a Document and map the fields
4. Create a Folder with the above created document 
5. Modify the uploaded document by removing all the map field and click on save button

Experienced Behavior : Observed that user is still able to see all the documents in folders when all the mapping is removed 
Expected Behavior : Ensure that application should not allow the user to view the documents in folders when all the mapping is removed

**Comment by ShaikASK** [comment]
Vinay: Fixed in Dev Environment, will be released in next build for QA (30-7-2018 3:58PM)

**Comment by MustafaASK** [comment]
01/08/2018 - Natasha Chouhan - We have retested this on the latest Release#3 Build 17 and observed that this is working as expected , Hence marking this to close
