### ISSUE TITLE
FF(61 ) / IE(11) : Email Templates : Save and cancel button is not visible properly 

### ISSUE THREAD

**Issue by MustafaASK** [ShaikASK/Testing#554]
Steps : To Replicate ; 

1. Launch the URL
2. Sign in as HR admin user
3. GO to Email Templates 
4. Create email template 
5. Try to save the above created email template 

Experienced Behavior : Observed that Save and cancel button is not visible properly (Refer Screen Shot) 
Expected Behavior : Ensure that application should display Save and cancel buttons properly

![data](https://user-images.githubusercontent.com/31955617/43249268-dfa1a518-90d7-11e8-9026-4bc410631eb1.jpg)

**Comment by ShaikASK** [comment]
Aditya: Fixed in Dev Environment, will released in the next build for QA (30-07-2018 3:47 PM)

**Comment by MustafaASK** [comment]
01/08/2018 - Natasha Chouhan - We have retested this on the latest Release#3 Build 17 and observed that this is working as expected , Hence marking this to close
