### ISSUE TITLE
Safari(11) : Extra space is observed in all the screens  except documents screen

### ISSUE THREAD

**Issue by ShaikASK** [ShaikASK/Testing#555]
Steps to Replicate : 

1. Launch the URL
2. Sign in as HR admin user
3. check the all the screens 

Experienced Behavior  : Observed that  extra space is displaying in all he screens except documents screen in safari (11) browser (Refer Screen Shot)
Expected Behavior : Ensure that application should display all the screens properly as like other browsers

New Hires : 
![screen shot 2018-07-26 at 5 35 37 pm](https://user-images.githubusercontent.com/31955617/43262714-c58f5ed2-90fe-11e8-8eca-4c31ac253a81.png)

Tasks : 
![screen shot 2018-07-26 at 5 36 01 pm](https://user-images.githubusercontent.com/31955617/43262715-c5bb9fd8-90fe-11e8-9bfc-957721818db1.png)

General Settings : 
![screen shot 2018-07-26 at 5 36 18 pm](https://user-images.githubusercontent.com/31955617/43262716-c5ec8e0e-90fe-11e8-809f-63ed97bfe6fb.png)

Dashboard : 
![screen shot 2018-07-26 at 5 34 46 pm](https://user-images.githubusercontent.com/31955617/43262713-c5630882-90fe-11e8-85fe-e8202266f406.png)

Workflows : 
![screen shot 2018-07-26 at 6 13 26 pm](https://user-images.githubusercontent.com/31955547/43263030-b805780e-90ff-11e8-9061-91e97dfb24fe.png)

Note : Candidate Module : Payroll Package web form 
![screen shot 2018-07-26 at 6 03 48 pm](https://user-images.githubusercontent.com/31955617/43262717-c617bec6-90fe-11e8-8ead-36b8055c5d97.png)

**Comment by ShaikASK** [comment]
Anil : Issue fixed in Dev Environment & Will be release to QA in next build (31-7--2018 2:32 PM)

**Comment by MustafaASK** [comment]
10/08/2018 - Natasha Chouhan - We have retested this on the latest Release#3 Build 19 and observed that this is working as expected , Hence marking this to close
