### ISSUE TITLE
Email Templates : Incorrect font is displayed as "Time New Roman" instead of "Verdana" 

### ISSUE THREAD

**Issue by MustafaASK** [ShaikASK/Testing#564]
Steps To Replicate : 

1. Launch the URL
2. Sign in as HR admin user
3. Create  "Email Template" 

Experienced Behavior : Observed that by default font is displayed as "Time New Roman"
Expected Behavior : Ensure that application should display default  font as "Verdana" instead of "Time New Roman"

**Comment by ShaikASK** [comment]
Vinay: Fixed in Dev Environment,Will be released to QA in next build (06-08-2018 12:37PM)

**Comment by MustafaASK** [comment]
09/08/2018 - Natasha Chouhan - We have retested this on the latest Release#3 Build 19 and observed that this is working as expected , Hence marking this to close
