### ISSUE TITLE
Initiate Onboarding : Company place holder is not updating in Email

### ISSUE THREAD

**Issue by ShaikASK** [ShaikASK/Testing#566]
Issue 01 : Company place holder is not updating in "Initiate Onboarding Email"

Steps To Replicate : 

1. Launch the URL
2. Sign in as HR admin user
3. Create email template for initiate Onboarding category  with "Company" place holder
4. Create New Hire and initiate it 
5. Check the triggered email 

Experienced Behavior : Observed that Company place holder is not updating in triggered "Initiate Onboarding Email"
Expected Behavior : Ensure that company logo place holder should be update when email triggered to candidate 

Issue 02 : Company city place holder is not updating in offer letter & in offer latter preview in initiate onboarding screen 

1. Launch the URL
2. Sign in as HR admin user
3. Create a "New Hire" and save it 
4. Try to Initiate the above created "New Hire" and check the preview of offer letter and also check the offer letter using candidate credentials after initiate onboarding 

Experienced Behavior : Observed that  company city place holder is not updating in offer letter & in offer latter preview in initiate onboarding screen 

Expected Behavior : Ensure that company city place holder should update in offer letter

**Comment by MustafaASK** [comment]
03/08/2018 - Natasha Chouhan - We have retested this on the latest Release#3 Build 18 and observed that this is working as expected , Hence marking this to close
