### ISSUE TITLE
Initiate Onboard : Edit Workflow : Horizontal scroll bar is being displayed upon clicking on search icon 

### ISSUE THREAD

**Issue by MustafaASK** [ShaikASK/Testing#572]
Steps To Replicate : 

1. Launch the URL
2. Sign in as HR admin user
3. Create New Hire and save it
4. Click on Initiate for the above created New Hire 
5. Navigate to "Initiate New Hire" screen 
6. Select the workflow from the drop down & click on edit icon displayed user workflows step 
7. Navigate to popup window 
8. Click on search icon to search folder name 

Experienced Behavior : Observed that horizontal scroll bar is being displayed upon clicking on search icon (Refer Screen)
Expected Behavior : Ensure that application should not display horizontal scroll bar 

![initiate onboard](https://user-images.githubusercontent.com/31955617/43629579-4a95fd30-971b-11e8-91df-09a8403a9fd3.jpg)

**Comment by ShaikASK** [comment]
Aditya: Fixed in Dev Environment,Will be released to QA in next build (06-08-2018 12:37PM)

**Comment by MustafaASK** [comment]
09/08/2018 - Natasha Chouhan - We have retested this on the latest Release#3 Build 19 and observed that this is working as expected , Hence marking this to close
