### ISSUE TITLE
Initiate Onboarding : Workflow dropdown : Numeric value is displayed upon performing mousehover operation on workflow drop down

### ISSUE THREAD

**Issue by MustafaASK** [ShaikASK/Testing#573]
Steps to Replicate : 

1. Launch the URL
2. Sign in as HR admin user
3. Create New Hire and save it
4. Click on Initiate for the above created New Hire 
5. Navigate to "Initiate New Hire" screen 
6. Mouse-over on workflow drop down 

Experienced Behavior : Observed that numeric value is displayed upon performing mousehover operation on workflow drop down from initiate onboard screen (Refer screen shot) 
Expected behavior ; Ensure that  application should not display numeric value when user perform mouse-over operation on workflow drop down from initiate onboard screen 

![d1](https://user-images.githubusercontent.com/31955617/43631478-f1f85bc2-9720-11e8-8c2c-02a288f6d8a0.png)

![d2](https://user-images.githubusercontent.com/31955617/43631495-f8fa1852-9720-11e8-8dc0-dc48e33d5426.jpg)

**Comment by ShaikASK** [comment]
Aditya: Fixed in Dev Environment,Will be released to QA in next build (06-08-2018 12:37PM)

**Comment by MustafaASK** [comment]
09/08/2018 - Natasha Chouhan - We have retested this on the latest Release#3 Build 19 and observed that this is working as expected , Hence marking this to close
