### ISSUE TITLE
Chrome (66) :  Weird behavior is observed upon selecting any radio option or check boxes in the application 

### ISSUE THREAD

**Issue by MustafaASK** [ShaikASK/Testing#574]
Steps To Replicate : 

1. Launch the URL
2. Sign in as HR admin user
3. Click on "Settings" 
4. Select users tab
5. Create user and select all radio options and check boxes 

Experienced Behavior : Observed that weird behavior [option is highlighted with a selected shade] is observed upon selecting any radio option or check boxes in the application when check with chrome(66) browser (Refer Screen shot)
Expected Behavior : Ensure that upon selecting the radio option application should not result in with a shade selected option .

![defect](https://user-images.githubusercontent.com/31955617/43631284-670bcc6a-9720-11e8-9037-f00a41923ee3.jpg)

**Comment by MustafaASK** [comment]
03/08/2018 - Natasha Chouhan - We have retested this on the latest Release#3 Build 18 and observed that this is working as expected , Hence marking this to close

**Comment by ShaikASK** [comment]
Dev Team:: It is the cache issue in QA's machines. It will work after deleting cache.

**Comment by MustafaASK** [comment]
Mahesh Varala - This is working as expected after removing cache from the browser , hence marking this to close
