### ISSUE TITLE
Dashboard : UI alignment of "Dashboard" screen is missing for New Hire section when there is no New Hire created 

### ISSUE THREAD

**Issue by MustafaASK** [ShaikASK/Testing#575]
Steps To Replicate : 

1. Launch the URL
2. Sign in as HR admin user
3. Navigate to 'Dashboard" screen 

Experienced Behavior : Observed that UI alignment of "Dashboard" screen is missing for New Hire section when there is no New Hire created (Refer Screen Shot)
Expected Behavior ; Ensure that application should display alignment of New Hire section properly on "Dashboard" screen 

![dashboard](https://user-images.githubusercontent.com/31955617/43641744-7362276c-9742-11e8-9473-73b9867d16fc.jpg)

**Comment by ShaikASK** [comment]
Anil: Fixed in Dev Environment,Will be released to QA in next build (06-08-2018 12:37PM)

**Comment by MustafaASK** [comment]
Mahesh Varala - Retested this on latest build and observed that it is working as expected , Hence marking this to close.
