### ISSUE TITLE
Review & Certify Screen :  Incorrect toaster message is displayed upon rejecting document 

### ISSUE THREAD

**Issue by MustafaASK** [ShaikASK/Testing#576]
Steps To Replicate : 

1. Launch the URL
2. Sign in as candidate credentials 
3. Click on "Get Started" 
4. Sign the Offer Letter
5. Navigate to "Common Details Form , fill the form click on submit
6. Navigate to other required web forms fill all the forms and click on next 
7. Navigate to "Dashboard" screen
8. Sign all the documents 
9. Sign in as HR admin user
10. Reject document uploaded by candidate from "Review & Certify" screen 
11. Check the toaster message 

Experienced Behavior : Observed that incorrect toaster message is displayed as "Detail notification send to Hr user and Hr admin" upon rejecting document from "Review & Certify" screen 

Expected Behavior : Ensure that message should be display as "Detail notification send to Candidate"  upon rejecting document from "Review & Certify" screen

**Comment by ShaikASK** [comment]
Aditya: Fixed in Dev Environment,Will be released to QA in next build (06-08-2018 01:20 PM)

**Comment by MustafaASK** [comment]
09/08/2018 - Natasha Chouhan - We have retested this on the latest Release#3 Build 19 and observed that this is working as expected , Hence marking this to close
