### ISSUE TITLE
My Accounts : - Profile pic logo uploaded in "PNG" format resulted to show in "Green" background  

### ISSUE THREAD

**Issue by MustafaASK** [ShaikASK/Testing#597]
Steps To  Replicate : 

1. Launch the URL
2. Sign in as Hr user 
3. Upload a logo with transparent background image 

Experienced Behavior : Observed that -Profile pic logo uploaded in "PNG" format resulted to show in "Green" background (Refer Screen Shot)

Expected Behavior : Ensure that application should display logo of company properly irrespective of the supported format

![ask](https://user-images.githubusercontent.com/31955617/44015239-b11dcf0e-9eed-11e8-8586-6bd38c6647b9.jpg)

**Comment by ShaikASK** [comment]
Dev Team : This is because of png type images. PNG image doesnt have background. So while storing png images in server the background color will be added by default. Tested in other websites also. Hence you can close this issue.

**Comment by MustafaASK** [comment]
13/08/2018 - Natasha Chouhan - We have retested this on the latest Release#3 Build 19 and observed that this is working as expected , Hence marking this to close
