### ISSUE TITLE
Payroll Form : Blank  "Account Number 1 & Routing Number 1" is displayed in the pdf form when user copy and paste account details 

### ISSUE THREAD

**Issue by MustafaASK** [ShaikASK/Testing#615]
Steps To Replicate : 

1.Launch the URL
2.Sign in as "Candidate Credentials" 
3.Click on "Get Started" form 
4.Sign the Offer Letter 
5.Navigate to "Common Details" form , fill the form and Click on "Submit" button
6.Navigate to "BGV" form fill  the form by clicking on next  and Navigate to Payroll form
7.Fill the form by entering data in all mandatory fields & enter account number 1 and then copy the number & paste in routing number 1 , Conform account number 1 and Conform routing number 1 
8.Click on Next 
9.Navigate  to "EEO" form fill the form and click on next 
10.Navigate to "Dashboard" screen 
11.Check the payroll pdf form 

Experienced Behavior : Observed that blank  ""Account Number 1 & Routing Number 1" is displayed in the pdf form when user copy and paste account details (Refer Screen Shot)
Expected Behavior : Ensure that application should not allow to copy and paste account details 

![payrollform](https://user-images.githubusercontent.com/31955617/44254307-0b7a0780-a220-11e8-9dc0-b658d1901b91.jpg)

**Comment by ShaikASK** [comment]
Anil: This issue is fixed and will be deployed in next build to QA (20-8-2018 2:38PM)

**Comment by MustafaASK** [comment]
Mahesh Varala- Retested this on the build#24 - Observed that it is working as expected , Hence marking this to close.
