### ISSUE TITLE
IE : View New Hire : UI issue - Thumbnail options are not visible 

### ISSUE THREAD

**Issue by MustafaASK** [ShaikASK/Testing#636]
1. Launch the url :
2. Sign in as "HR Admin" user
3. Go to "NEW HIRES" menu
4. Click on the 3 dots options on the new hire thumb nail

Experienced Behavior : Observed that except "View Hire" there are no other options are displayed 
Expected Behavior :  Ensure that Thumbnail options are visible properly upon mouse hovering 
Attaching screen shot for reference
![new hire _ie issue](https://user-images.githubusercontent.com/31955617/45215866-5a193f80-b2bc-11e8-9b33-b41aa8c60326.jpg)

**Comment by ShaikASK** [comment]
Vinay: This issue is similar to #261 .

**Comment by MustafaASK** [comment]
Mahesh Varala- Retested this on the latest build #28 and observed that it is working as expected , Hence closing the defect
