### ISSUE TITLE
 Few CK editor options are missing in  Dashboard , Initiate onboarding & Email Templates  screens

### ISSUE THREAD

**Issue by MustafaASK** [ShaikASK/Testing#801]
Steps To Replicate : 

1.Launch the URL
2.Sign in as HR admin user 
3.Check CK editor for send email template from dashboard screen 
4.Check CK editor for  email template 
5.Check CK Edit for Initiate On boarding screen 

Experienced Behavior : Observed that following options are missed from Dashboard screen, initiate On boarding screen & email template screen Ck editor (Refer Screen Shot) 

- Insert/Remove numbered list 
- Insert  & Remove Bulleted List 
- Subscripts & Superscripts
- Background Color 

Expected Behavior : Ensure that application should display all the options of ck editor in the respective screens 

![email templates](https://user-images.githubusercontent.com/31955617/47984485-c073e000-e0fc-11e8-8994-eedc6d7665db.png)

**Comment by ShaikASK** [comment]
This will be done in the build after next coming build (#41)

**Comment by MustafaASK** [comment]
21/11/2018 - Natasha Chouhan - We have retested this on the latest Release#3 Build 41 and observed that this is working as expected , Hence marking this to close
